# Linguagem Utilizada para Desenvolver a Aplicação
language: python

# Versão que a aplicação suporta.
python:
  - "3.7.9"

os: linux
dist: xenial

before_install:
- openssl aes-256-cbc -K $encrypted_458499fd1b95_key -iv $encrypted_458499fd1b95_iv
  -in lab-devops-cloud-1-95cfca154eac.json.enc -out ../lab-devops-cloud-1-95cfca154eac.json
  -d

addons:
  sonarcloud:
    organization: pjalbuquerque
    token: ${SONAR_TOKEN}

jobs:
  include:
    - stage: Build

      name: "Testes Unitarios"
      # Instalação de Módulos que são necessários para a Aplicação.
      install:
        - pip3 install flask flask-wtf coverage
      script:  # Defini o script de Teste que deve rodar toda vez que o código for alterado.
        - coverage run test.py || travis_terminate 1;
        - coverage report app.py || travis_terminate 1;
        - coverage xml app.py || travis_terminate 1;
        - python -m unittest -v test || travis_terminate 1;
        - sonar-scanner || travis_terminate 1;

    - stage: STG Deploy
      script: skip
      # Definir o Deploy no Heroku
      deploy:
        provider: heroku
        strategy: api
        api_key: $HEROKU_API_KEY
        edge: true
        app: devopslab-pauloalbuquerque
        on:
          branch: main

    - stage: STG TEST
      script:
        - curl https://devopslab-pauloalbuquerque.herokuapp.com/ | grep Paulo || travis_terminate 1;

    - stage: PROD Deploy
      script: skip
      # Definir o Deploy no Google Cloud
      deploy:
        provider: gae
        keyfile: ../lab-devops-cloud-1-95cfca154eac.json
        project: lab-devops-cloud-1
        on:
          branch: main

    - stage: PROD TEST
      script:
        - curl https://lab-devops-cloud-1.uc.r.appspot.com/ | grep Paulo || travis_terminate 1;

